app:
  chat:
    maxMembers: 100

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
spring:
  data:
    mongodb:
      username: bhanu
      password: bhanu1489
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
    redis:
      host: localhost
      port: 6379
server:
  port: 8088
